### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by rickywu** [pingcap/tidb.ai#210]
Config embedding model and click advanced settings got this error.

browser console got this:

```
Error: Illegal argument
    at u (723.2c2e18e7fe5caa03.js:416:468224)
    at n.setValue (723.2c2e18e7fe5caa03.js:416:1651695)
    at sF.setValue (723.2c2e18e7fe5caa03.js:416:1136477)
    at 1970-70388ac996ff77fe.js:1:4617
    at aW (6ba8c1ff-0cff7c2a33d42ee9.js:1:73245)
    at oe (6ba8c1ff-0cff7c2a33d42ee9.js:1:84686)
    at ol (6ba8c1ff-0cff7c2a33d42ee9.js:1:85324)
    at or (6ba8c1ff-0cff7c2a33d42ee9.js:1:85208)
    at ol (6ba8c1ff-0cff7c2a33d42ee9.js:1:85304)
    at or (6ba8c1ff-0cff7c2a33d42ee9.js:1:85208)
```

I config LLM with json config successfully with local Qwen LLM, can I use this config other embedding model?
![image](https://github.com/user-attachments/assets/78adfe35-0c4c-4c3c-ad3e-517586fad8f9)

**Comment by sykp241095** [comment]
@Mini256 ptal

**Comment by 634750802** [comment]
It's a frontend bug opening the json editor. And we only support openai embedding with 1536 dim currently.

**Comment by 634750802** [comment]
should fix in https://github.com/pingcap/tidb.ai/commit/1f2ddb043a5ef06371d8ab513fb7001231ca9e16
