### ISSUE TITLE
bug: FileExistsError: [Errno 17] File exists

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#258]
This error occurs while I am upgrading by following: https://tidb.ai/docs/deploy-with-docker#upgrade

```plain
backend-1     | [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
backend-1     | [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
backend-1     | [2024-09-03 02:21:27 +0000] [14] [ERROR] Exception in worker process
backend-1     | Traceback (most recent call last):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 65, in __init__
backend-1     |     nltk.data.find("tokenizers/punkt")
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/data.py", line 579, in find
backend-1     |     raise LookupError(resource_not_found)
backend-1     | LookupError:
backend-1     | **********************************************************************
backend-1     |   Resource punkt not found.
backend-1     |   Please use the NLTK Downloader to obtain the resource:
backend-1     |
backend-1     |   >>> import nltk
backend-1     |   >>> nltk.download('punkt')
backend-1     |
backend-1     |   For more information see: https://www.nltk.org/data.html
backend-1     |
backend-1     |   Attempted to load tokenizers/punkt
backend-1     |
backend-1     |   Searched in:
backend-1     |     - '/root/nltk_data'
backend-1     |     - '/usr/local/nltk_data'
backend-1     |     - '/usr/local/share/nltk_data'
backend-1     |     - '/usr/local/lib/nltk_data'
backend-1     |     - '/usr/share/nltk_data'
backend-1     |     - '/usr/local/share/nltk_data'
backend-1     |     - '/usr/lib/nltk_data'
backend-1     |     - '/usr/local/lib/nltk_data'
backend-1     |     - '/usr/local/lib/python3.11/site-packages/llama_index/core/_static/nltk_cache'
backend-1     | **********************************************************************
backend-1     |
backend-1     |
backend-1     | During handling of the above exception, another exception occurred:
backend-1     |
backend-1     | Traceback (most recent call last):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
backend-1     |     worker.init_process()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process
backend-1     |     super().init_process()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
backend-1     |     self.load_wsgi()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
backend-1     |     self.wsgi = self.app.wsgi()
backend-1     |                 ^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend-1     |     self.callable = self.load()
backend-1     |                     ^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
backend-1     |     return self.load_wsgiapp()
backend-1     |            ^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
backend-1     |     return util.import_app(self.app_uri)
backend-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
backend-1     |     mod = importlib.import_module(module)
backend-1     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend-1     |     return _bootstrap._gcd_import(name[level:], package, level)
backend-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend-1     |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend-1     |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend-1     |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend-1     |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend-1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-1     |   File "/app/main.py", line 14, in <module>
backend-1     |     from app.api.main import api_router
backend-1     |   File "/app/app/api/main.py", line 3, in <module>
backend-1     |     from app.api.routes import (
backend-1     |   File "/app/app/api/routes/index.py", line 5, in <module>
backend-1     |     from app.api.deps import SessionDep
backend-1     |   File "/app/app/api/deps.py", line 7, in <module>
backend-1     |     from app.models import User
backend-1     |   File "/app/app/models/__init__.py", line 19, in <module>
backend-1     |     from .document import Document, DocIndexTaskStatus
backend-1     |   File "/app/app/models/document.py", line 5, in <module>
backend-1     |     from llama_index.core.schema import Document as LlamaDocument
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/__init__.py", line 10, in <module>
backend-1     |     from llama_index.core.base.response.schema import Response
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/base/response/schema.py", line 9, in <module>
backend-1     |     from llama_index.core.schema import NodeWithScore
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/schema.py", line 18, in <module>
backend-1     |     from llama_index.core.utils import SAMPLE_TEXT, truncate_text
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 89, in <module>
backend-1     |     globals_helper = GlobalsHelper()
backend-1     |                      ^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 67, in __init__
backend-1     |     nltk.download("punkt_tab", download_dir=self._nltk_data_dir)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 774, in download
backend-1     |     for msg in self.incr_download(info_or_id, download_dir, force):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 642, in incr_download
backend-1     |     yield from self._download_package(info, download_dir, force)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 733, in _download_package
backend-1     |     for msg in _unzip_iter(filepath, zipdir, verbose=False):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 2250, in _unzip_iter
backend-1     |     zf.extractall(root)
backend-1     |   File "/usr/local/lib/python3.11/zipfile.py", line 1701, in extractall
backend-1     |     self._extract_member(zipinfo, path, pwd)
backend-1     |   File "/usr/local/lib/python3.11/zipfile.py", line 1751, in _extract_member
backend-1     |     os.mkdir(targetpath)
backend-1     | FileExistsError: [Errno 17] File exists: '/usr/local/lib/python3.11/site-packages/llama_index/core/_static/nltk_cache/tokenizers/punkt_tab/finnish'
backend-1     | [2024-09-03 02:21:27 +0000] [14] [INFO] Worker exiting (pid: 14)
backend-1     | [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
backend-1     | [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
backend-1     | [2024-09-03 02:21:28 +0000] [9] [ERROR] Exception in worker process
backend-1     | Traceback (most recent call last):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 65, in __init__
backend-1     |     nltk.data.find("tokenizers/punkt")
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/data.py", line 579, in find
backend-1     |     raise LookupError(resource_not_found)
backend-1     | LookupError:
backend-1     | **********************************************************************
backend-1     |   Resource punkt not found.
backend-1     |   Please use the NLTK Downloader to obtain the resource:
backend-1     |
backend-1     |   >>> import nltk
backend-1     |   >>> nltk.download('punkt')
backend-1     |
backend-1     |   For more information see: https://www.nltk.org/data.html
backend-1     |
backend-1     |   Attempted to load tokenizers/punkt
backend-1     |
backend-1     |   Searched in:
backend-1     |     - '/root/nltk_data'
backend-1     |     - '/usr/local/nltk_data'
backend-1     |     - '/usr/local/share/nltk_data'
backend-1     |     - '/usr/local/lib/nltk_data'
backend-1     |     - '/usr/share/nltk_data'
backend-1     |     - '/usr/local/share/nltk_data'
backend-1     |     - '/usr/lib/nltk_data'
backend-1     |     - '/usr/local/lib/nltk_data'
backend-1     |     - '/usr/local/lib/python3.11/site-packages/llama_index/core/_static/nltk_cache'
backend-1     | **********************************************************************
backend-1     |
backend-1     |
backend-1     | During handling of the above exception, another exception occurred:
backend-1     |
backend-1     | Traceback (most recent call last):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
backend-1     |     worker.init_process()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process
backend-1     |     super().init_process()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
backend-1     |     self.load_wsgi()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
backend-1     |     self.wsgi = self.app.wsgi()
backend-1     |                 ^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend-1     |     self.callable = self.load()
backend-1     |                     ^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
backend-1     |     return self.load_wsgiapp()
backend-1     |            ^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
backend-1     |     return util.import_app(self.app_uri)
backend-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
backend-1     |     mod = importlib.import_module(module)
backend-1     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend-1     |     return _bootstrap._gcd_import(name[level:], package, level)
backend-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend-1     |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend-1     |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend-1     |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend-1     |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend-1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-1     |   File "/app/main.py", line 14, in <module>
backend-1     |     from app.api.main import api_router
backend-1     |   File "/app/app/api/main.py", line 3, in <module>
backend-1     |     from app.api.routes import (
backend-1     |   File "/app/app/api/routes/index.py", line 5, in <module>
backend-1     |     from app.api.deps import SessionDep
backend-1     |   File "/app/app/api/deps.py", line 7, in <module>
backend-1     |     from app.models import User
backend-1     |   File "/app/app/models/__init__.py", line 19, in <module>
backend-1     |     from .document import Document, DocIndexTaskStatus
backend-1     |   File "/app/app/models/document.py", line 5, in <module>
backend-1     |     from llama_index.core.schema import Document as LlamaDocument
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/__init__.py", line 10, in <module>
backend-1     |     from llama_index.core.base.response.schema import Response
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/base/response/schema.py", line 9, in <module>
backend-1     |     from llama_index.core.schema import NodeWithScore
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/schema.py", line 18, in <module>
backend-1     |     from llama_index.core.utils import SAMPLE_TEXT, truncate_text
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 89, in <module>
backend-1     |     globals_helper = GlobalsHelper()
backend-1     |                      ^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 67, in __init__
backend-1     |     nltk.download("punkt_tab", download_dir=self._nltk_data_dir)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 774, in download
backend-1     |     for msg in self.incr_download(info_or_id, download_dir, force):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 642, in incr_download
backend-1     |     yield from self._download_package(info, download_dir, force)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 733, in _download_package
backend-1     |     for msg in _unzip_iter(filepath, zipdir, verbose=False):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 2250, in _unzip_iter
backend-1     |     zf.extractall(root)
backend-1     |   File "/usr/local/lib/python3.11/zipfile.py", line 1701, in extractall
backend-1     |     self._extract_member(zipinfo, path, pwd)
backend-1     |   File "/usr/local/lib/python3.11/zipfile.py", line 1751, in _extract_member
backend-1     |     os.mkdir(targetpath)
backend-1     | FileExistsError: [Errno 17] File exists: '/usr/local/lib/python3.11/site-packages/llama_index/core/_static/nltk_cache/tokenizers/punkt_tab/greek'
backend-1     | [2024-09-03 02:21:28 +0000] [9] [INFO] Worker exiting (pid: 9)
backend-1     | [2024-09-03 02:21:28 +0000] [7] [ERROR] Exception in worker process
backend-1     | Traceback (most recent call last):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 65, in __init__
backend-1     |     nltk.data.find("tokenizers/punkt")
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/data.py", line 579, in find
backend-1     |     raise LookupError(resource_not_found)
backend-1     | LookupError:
backend-1     | **********************************************************************
backend-1     |   Resource punkt not found.
backend-1     |   Please use the NLTK Downloader to obtain the resource:
backend-1     |
backend-1     |   >>> import nltk
backend-1     |   >>> nltk.download('punkt')
backend-1     |
backend-1     |   For more information see: https://www.nltk.org/data.html
backend-1     |
backend-1     |   Attempted to load tokenizers/punkt
backend-1     |
backend-1     |   Searched in:
backend-1     |     - '/root/nltk_data'
backend-1     |     - '/usr/local/nltk_data'
backend-1     |     - '/usr/local/share/nltk_data'
backend-1     |     - '/usr/local/lib/nltk_data'
backend-1     |     - '/usr/share/nltk_data'
backend-1     |     - '/usr/local/share/nltk_data'
backend-1     |     - '/usr/lib/nltk_data'
backend-1     |     - '/usr/local/lib/nltk_data'
backend-1     |     - '/usr/local/lib/python3.11/site-packages/llama_index/core/_static/nltk_cache'
backend-1     | **********************************************************************
backend-1     |
backend-1     |
backend-1     | During handling of the above exception, another exception occurred:
backend-1     |
backend-1     | Traceback (most recent call last):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
backend-1     |     worker.init_process()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process
backend-1     |     super().init_process()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
backend-1     |     self.load_wsgi()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
backend-1     |     self.wsgi = self.app.wsgi()
backend-1     |                 ^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend-1     |     self.callable = self.load()
backend-1     |                     ^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
backend-1     |     return self.load_wsgiapp()
backend-1     |            ^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
backend-1     |     return util.import_app(self.app_uri)
backend-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
backend-1     |     mod = importlib.import_module(module)
backend-1     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend-1     |     return _bootstrap._gcd_import(name[level:], package, level)
backend-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend-1     |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend-1     |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend-1     |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend-1     |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend-1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-1     |   File "/app/main.py", line 14, in <module>
backend-1     |     from app.api.main import api_router
backend-1     |   File "/app/app/api/main.py", line 3, in <module>
backend-1     |     from app.api.routes import (
backend-1     |   File "/app/app/api/routes/index.py", line 5, in <module>
backend-1     |     from app.api.deps import SessionDep
backend-1     |   File "/app/app/api/deps.py", line 7, in <module>
backend-1     |     from app.models import User
backend-1     |   File "/app/app/models/__init__.py", line 19, in <module>
backend-1     |     from .document import Document, DocIndexTaskStatus
backend-1     |   File "/app/app/models/document.py", line 5, in <module>
backend-1     |     from llama_index.core.schema import Document as LlamaDocument
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/__init__.py", line 10, in <module>
backend-1     |     from llama_index.core.base.response.schema import Response
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/base/response/schema.py", line 9, in <module>
backend-1     |     from llama_index.core.schema import NodeWithScore
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/schema.py", line 18, in <module>
backend-1     |     from llama_index.core.utils import SAMPLE_TEXT, truncate_text
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 89, in <module>
backend-1     |     globals_helper = GlobalsHelper()
backend-1     |                      ^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 67, in __init__
backend-1     |     nltk.download("punkt_tab", download_dir=self._nltk_data_dir)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 774, in download
backend-1     |     for msg in self.incr_download(info_or_id, download_dir, force):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 642, in incr_download
backend-1     |     yield from self._download_package(info, download_dir, force)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 733, in _download_package
backend-1     |     for msg in _unzip_iter(filepath, zipdir, verbose=False):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/nltk/downloader.py", line 2250, in _unzip_iter
backend-1     |     zf.extractall(root)
backend-1     |   File "/usr/local/lib/python3.11/zipfile.py", line 1701, in extractall
backend-1     |     self._extract_member(zipinfo, path, pwd)
backend-1     |   File "/usr/local/lib/python3.11/zipfile.py", line 1751, in _extract_member
backend-1     |     os.mkdir(targetpath)
backend-1     | FileExistsError: [Errno 17] File exists: '/usr/local/lib/python3.11/site-packages/llama_index/core/_static/nltk_cache/tokenizers/punkt_tab/norwegian'

```

**Comment by wd0517** [comment]
It should be resolved by https://github.com/pingcap/tidb.ai/commit/2f6138e9383453a5e2f5e7444d36477d4d99a0ce
