### ISSUE TITLE
bug: Unknown column 'chat_messages.graph_data' in 'field list

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#310]
```txt
backend-1     | [SQL: SELECT chat_messages.created_at, chat_messages.updated_at, chat_messages.id, chat_messages.ordinal, chat_messages.`role`, chat_messages.content, chat_messages.error, chat_messages.sources, chat_messages.graph_data, chat_messages.trace_url, chat_messages.finished_at, chat_messages.chat_id, chat_messages.user_id, chat_engines_1.created_at AS created_at_1, chat_engines_1.updated_at AS updated_at_1, chat_engines_1.id AS id_1, chat_engines_1.name, chat_engines_1.engine_options, chat_engines_1.llm_id, chat_engines_1.fast_llm_id, chat_engines_1.reranker_id, chat_engines_1.is_default, chat_engines_1.deleted_at, users_1.created_at AS created_at_2, users_1.updated_at AS updated_at_2, users_1.id AS id_2, users_1.email, users_1.hashed_password, users_1.is_active, users_1.is_superuser, users_1.is_verified, chats_1.created_at AS created_at_3, chats_1.updated_at AS updated_at_3, chats_1.id AS id_3, chats_1.title, chats_1.engine_id, chats_1.engine_options AS engine_options_1, chats_1.deleted_at AS deleted_at_1, chats_1.user_id AS user_id_1, chats_1.browser_id, users_2.created_at AS created_at_4, users_2.updated_at AS updated_at_4, users_2.id AS id_4, users_2.email AS email_1, users_2.hashed_password AS hashed_password_1, users_2.is_active AS is_active_1, users_2.is_superuser AS is_superuser_1, users_2.is_verified AS is_verified_1
backend-1     | FROM chat_messages LEFT OUTER JOIN chats AS chats_1 ON chat_messages.chat_id = chats_1.id LEFT OUTER JOIN chat_engines AS chat_engines_1 ON chats_1.engine_id = chat_engines_1.id LEFT OUTER JOIN users AS users_1 ON chats_1.user_id = users_1.id LEFT OUTER JOIN users AS users_2 ON chat_messages.user_id = users_2.id
backend-1     | WHERE chat_messages.chat_id = %(chat_id_1)s ORDER BY chat_messages.ordinal DESC]
backend-1     | [parameters: {'chat_id_1': '019236c38ca2766a9be19714b70afd97'}]
backend-1     | (Background on this error at: https://sqlalche.me/e/20/e3q8)
backend-1     | Traceback (most recent call last):
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
backend-1     |     self.dialect.do_execute(
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
backend-1     |     cursor.execute(statement, parameters)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
backend-1     |     result = self._query(query)
backend-1     |              ^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
backend-1     |     conn.query(q)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
backend-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
backend-1     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
backend-1     |     result.read()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
backend-1     |     first_packet = self.connection._read_packet()
backend-1     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
backend-1     |     packet.raise_for_error()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
backend-1     |     err.raise_mysql_exception(self._data)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
backend-1     |     raise errorclass(errno, errval)
backend-1     | pymysql.err.OperationalError: (1054, "Unknown column 'chat_messages.graph_data' in 'field list'")
backend-1     |
backend-1     | The above exception was the direct cause of the following exception:
backend-1     |
backend-1     | Traceback (most recent call last):
backend-1     |   File "/app/app/rag/chat.py", line 88, in chat
backend-1     |     for event in self._chat(chat_messages, chat_id):
backend-1     |   File "/app/app/rag/chat.py", line 172, in _chat
backend-1     |     db_user_message = chat_repo.create_message(
backend-1     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/app/app/repositories/chat.py", line 85, in create_message
backend-1     |     last_message = self.get_last_message(session, chat)
backend-1     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/app/app/repositories/chat.py", line 49, in get_last_message
backend-1     |     return session.exec(
backend-1     |            ^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlmodel/orm/session.py", line 66, in exec
backend-1     |     results = super().execute(
backend-1     |               ^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
backend-1     |     return self._execute_internal(
backend-1     |            ^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2236, in _execute_internal
backend-1     |     result: Result[Any] = compile_state_cls.orm_execute_statement(
backend-1     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
backend-1     |     result = conn.execute(
backend-1     |              ^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
backend-1     |     return meth(
backend-1     |            ^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
backend-1     |     return connection._execute_clauseelement(
backend-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
backend-1     |     ret = self._execute_context(
backend-1     |           ^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
backend-1     |     return self._exec_single_context(
backend-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
backend-1     |     self._handle_dbapi_exception(
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
backend-1     |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
backend-1     |     self.dialect.do_execute(
backend-1     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
backend-1     |     cursor.execute(statement, parameters)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
backend-1     |     result = self._query(query)
backend-1     |              ^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
backend-1     |     conn.query(q)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
backend-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
backend-1     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
backend-1     |     result.read()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
backend-1     |     first_packet = self.connection._read_packet()
backend-1     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
backend-1     |     packet.raise_for_error()
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
backend-1     |     err.raise_mysql_exception(self._data)
backend-1     |   File "/usr/local/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
backend-1     |     raise errorclass(errno, errval)
backend-1     | sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'chat_messages.graph_data' in 'field list'")
```

**Comment by wd0517** [comment]
Migrate db after upgrade docker image should resolve this error.
